name: Run integration test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout workbench
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Checkout isle-site-template
        uses: actions/checkout@v4
        with:
          repository: Islandora-Devops/isle-site-template
          path: isle-site-template

      - name: Install mkcert
        run: |-
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert

      - name: Start islandora-starter-site
        working-directory: isle-site-template
        run: ./tests/init-template-starter.sh
        env:
          ISLANDORA_TAG: main
          ISLANDORA_STARTER_REF: "heads/main"
          ISLANDORA_STARTER_OWNER: "Islandora-Devops"

      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          python setup.py install

      - name: Run unittests  
        run: |  
          python tests/islandora_tests.py
